### PR TITLE
feat: update to auto-launch 0.3 with arbitrary args support

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

**Comment by amrbashir** [comment]
looks like the upsteam crate is using `anyhow` instead of `thiserror`, will open a PR upstream and update later when they release a new version.

**Comment by lucasfernog** [comment]
We could still handle it here instead.

**Comment by amrbashir** [comment]
wouldn't this mean the plugin needs to depend on `anyhow` too ?

**Comment by amrbashir** [comment]
upstream PR to switch to `thiserror` has been merged but not sure when it is gonna be published.

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
